export const HANDLE_NUMBER = "HANDLE_NUMBER";
export const HANDLE_CE = 'HANDLE_CE';
export const HANDLE_C = 'HANDLE_C';
export const HANDLE_DO_ARITHMETIC = 'HANDLE_DO_ARITHMETIC';
export const HANDLE_FRACTION = 'HANDLE_FRACTION';
export const HANDLE_INVERSE_FRACTION = 'HANDLE_INVERSE_FRACTION';
export const HANDLE_SQRT = 'HANDLE_SQRT';
export const HANDLE_EQUAL = 'HANDLE_EQUAL';